//@ui5-bundle sap/ui/demo/basicTemplate/Component-preload.js
sap.ui.require.preload({
	"sap/ui/demo/basicTemplate/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(e,i,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
},
	"sap/ui/demo/basicTemplate/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/demo/basicTemplate/model/formatter"],function(e,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.controller.App",{formatter:t,onInit:function(){}})});
},
	"sap/ui/demo/basicTemplate/controller/Home.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","../model/formatter"],function(e,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.controller.Home",{formatter:t,onInit:function(){}})});
},
	"sap/ui/demo/basicTemplate/i18n/i18n.properties":'title=Basic Template\nappTitle=Basic Template\nappDescription=Blank app as starting point for your app development',
	"sap/ui/demo/basicTemplate/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"sap.ui.demo.basicTemplate","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"sap.ui.demo.basicTemplate.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sap.ui.demo.basicTemplate.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"sap.ui.demo.basicTemplate.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"home","target":["home"]}],"targets":{"home":{"viewName":"Home","viewId":"home","viewLevel":1,"title":"{i18n>title}"}}}}}',
	"sap/ui/demo/basicTemplate/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"sap/ui/demo/basicTemplate/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"sap/ui/demo/basicTemplate/view/App.view.xml":'<mvc:View displayBlock="true" xmlns="sap.m" xmlns:mvc="sap.ui.core.mvc" controllerName="sap.ui.demo.basicTemplate.controller.App"><App id="app" /></mvc:View>\n',
	"sap/ui/demo/basicTemplate/view/Home.view.xml":'<mvc:View controllerName="sap.ui.demo.basicTemplate.controller.Home" displayBlock="true" xmlns="sap.m" xmlns:uxap="sap.uxap" xmlns:mvc="sap.ui.core.mvc"><uxap:ObjectPageLayout id="ObjectPageLayout" showTitleInHeaderContent="true" showEditHeaderButton="true" editHeaderButtonPress="handleEditBtnPress" upperCaseAnchorBar="false"><uxap:footer /><uxap:headerContent /><uxap:headerTitle><uxap:ObjectPageDynamicHeaderTitle><uxap:breadcrumbs><Breadcrumbs id="breadcrumbsId" currentLocationText="Object Page Example"><Link text="Page 1 a very long link" press="handleLink1Press" /><Link text="Page 2 long link" press="handleLink2Press" /></Breadcrumbs></uxap:breadcrumbs><uxap:expandedHeading><HBox><Title text="Lukas Rausch" wrapping="true" /><ObjectMarker type="Favorite" class="sapUiTinyMarginBegin" /></HBox></uxap:expandedHeading><uxap:snappedHeading><FlexBox fitContainer="true" alignItems="Center"><Avatar src="./test-resources/sap/uxap/images/imageID_275314.png" class="sapUiTinyMarginEnd" /><Title text="Denise Smith" wrapping="true" /></FlexBox></uxap:snappedHeading><uxap:snappedHeading><FlexBox fitContainer="true" alignItems="Center"><Avatar src="../img/ich.jpg" class="sapUiTinyMarginEnd" /><Title text="Denise Smith" wrapping="true" /></FlexBox></uxap:snappedHeading><uxap:expandedContent><Text text="Senior UI Enwtickler" /></uxap:expandedContent><uxap:snappedContent><Text text="Senior UI Entwickler" /></uxap:snappedContent><uxap:snappedTitleOnMobile><Title text="Senior UI Entwickler" /></uxap:snappedTitleOnMobile></uxap:ObjectPageDynamicHeaderTitle></uxap:headerTitle><uxap:landmarkInfo /><uxap:sections /></uxap:ObjectPageLayout></mvc:View>\n'
});
