//@ui5-bundle sap/ui/demo/basicTemplate/Component-preload.js
sap.ui.require.preload({
	"sap/ui/demo/basicTemplate/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(e,i,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
},
	"sap/ui/demo/basicTemplate/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/demo/basicTemplate/model/formatter"],function(e,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.controller.App",{formatter:t,onInit:function(){}})});
},
	"sap/ui/demo/basicTemplate/controller/Home.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","../model/formatter"],function(e,t){"use strict";return e.extend("sap.ui.demo.basicTemplate.controller.Home",{formatter:t,onInit:function(){}})});
},
	"sap/ui/demo/basicTemplate/i18n/i18n.properties":'title=Basic Template\nappTitle=Basic Template\nappDescription=Blank app as starting point for your app development',
	"sap/ui/demo/basicTemplate/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"sap.ui.demo.basicTemplate","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"sap.ui.demo.basicTemplate.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sap.ui.demo.basicTemplate.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"sap.ui.demo.basicTemplate.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"home","target":["home"]}],"targets":{"home":{"viewName":"Home","viewId":"home","viewLevel":1,"title":"{i18n>title}"}}}}}',
	"sap/ui/demo/basicTemplate/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"sap/ui/demo/basicTemplate/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"sap/ui/demo/basicTemplate/view/App.view.xml":'<mvc:View displayBlock="true" xmlns="sap.m" xmlns:mvc="sap.ui.core.mvc" controllerName="sap.ui.demo.basicTemplate.controller.App"><App id="app" /></mvc:View>\n',
	"sap/ui/demo/basicTemplate/view/Home.view.xml":'<mvc:View\n\tcontrollerName="sap.ui.demo.basicTemplate.controller.Home"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:uxap="sap.uxap"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:layout="sap.ui.layout"\n><uxap:ObjectPageLayout\n\t\tid="ObjectPageLayout"\n\t\tshowTitleInHeaderContent="true"\n\t\tshowEditHeaderButton="true"\n\t\tupperCaseAnchorBar="false"\n\t><uxap:footer/><uxap:headerContent><FlexBox wrap="Wrap"><Avatar\n\t\t\t\t\tclass="sapUiSmallMarginEnd"\n\t\t\t\t\tsrc="./img/ich.jpg"\n\t\t\t\t\tdisplaySize="XL"\n\t\t\t\t/><layout:VerticalLayout class="sapUiSmallMarginBeginEnd"><VBox class="sapUiSmallMarginBeginEnd"><HBox><Image src="./img/twitter.png"/><Link\n\t\t\t\t\t\t\t\thref="https://twitter.com/TheRealLuga"\n\t\t\t\t\t\t\t\ttext="@TheRealLuga"\n\t\t\t\t\t\t\t\tclass="sapUiSmallMarginBegin"\n\t\t\t\t\t\t\t/></HBox><HBox><Image src="./img/github.png"/><Link\n\t\t\t\t\t\t\t\thref="https://github.com/xLuga?tab=repositories"\n\t\t\t\t\t\t\t\ttext="xLuga"\n\t\t\t\t\t\t\t\tclass="sapUiSmallMarginBegin"\n\t\t\t\t\t\t\t/></HBox><HBox><Image src="./img/linkedin.png"/><Link\n\t\t\t\t\t\t\t\thref="https://www.linkedin.com/in/lukas-rausch-158a69250/"\n\t\t\t\t\t\t\t\ttext="Lukas Rausch"\n\t\t\t\t\t\t\t\tclass="sapUiSmallMarginBegin"\n\t\t\t\t\t\t\t/></HBox><HBox><Image src="./img/whatsapp.png"/><Link\n\t\t\t\t\t\t\t\ttext="+49 151 688 06 766"\n\t\t\t\t\t\t\t\tclass="sapUiSmallMarginBegin"\n\t\t\t\t\t\t\t/></HBox><HBox><Image src="./img/email.png"/><Link\n\t\t\t\t\t\t\t\ttext="lukas_rausch@gmx.de"\n\t\t\t\t\t\t\t\tclass="sapUiSmallMarginBegin"\n\t\t\t\t\t\t\t/></HBox></VBox></layout:VerticalLayout></FlexBox></uxap:headerContent><uxap:headerTitle><uxap:ObjectPageDynamicHeaderTitle><uxap:breadcrumbs><Breadcrumbs currentLocationText="Die Seite wurde mit OpenUi5 entworfen"/></uxap:breadcrumbs><uxap:expandedHeading><HBox><Title\n\t\t\t\t\t\t\ttext="Lukas Rausch"\n\t\t\t\t\t\t\twrapping="true"\n\t\t\t\t\t\t/><ObjectMarker\n\t\t\t\t\t\t\ttype="Favorite"\n\t\t\t\t\t\t\tclass="sapUiTinyMarginBegin"\n\t\t\t\t\t\t/></HBox></uxap:expandedHeading><uxap:snappedHeading><FlexBox\n\t\t\t\t\t\tfitContainer="true"\n\t\t\t\t\t\talignItems="Center"\n\t\t\t\t\t><Avatar\n\t\t\t\t\t\t\tsrc="./img/ich.jpg"\n\t\t\t\t\t\t\tclass="sapUiTinyMarginEnd"\n\t\t\t\t\t\t/><Title\n\t\t\t\t\t\t\ttext="Lukas Rausch"\n\t\t\t\t\t\t\twrapping="true"\n\t\t\t\t\t\t/></FlexBox></uxap:snappedHeading><uxap:expandedContent><Text text="Senior UI Entwickler - Fulda, DE"/></uxap:expandedContent><uxap:snappedContent><Text text="Senior UI Entwickler - Fulda, DE"/></uxap:snappedContent><uxap:snappedTitleOnMobile><Title text="Senior UI Entwickler - Fulda, DE"/></uxap:snappedTitleOnMobile></uxap:ObjectPageDynamicHeaderTitle></uxap:headerTitle><uxap:landmarkInfo/><uxap:sections/></uxap:ObjectPageLayout></mvc:View>'
});
